---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "Kubelet"
        metrics_path: "/metrics/cadvisor"
        scheme: "https"
        honor_timestamps: true
        bearer_token_file: "/etc/prometheus/token"
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['<host>:10250']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/config
            - name: token-volume
              mountPath: /etc/prometheus/token
              subPath: token
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: token-volume
          secret:
            secretName: prom-api-user-secret
            items:
              - key: token
                path: token
        - name: prometheus-empty-dir
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
  clusterIP: None