---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka-init
  name: kafka-init-orderbook-job
  namespace: orderbook
spec:
  template:
    metadata:
      labels:
        app: kafka-init
    spec:
      containers:
      - name: kafka-init-orderbook
        image: local/kafka-init
        imagePullPolicy: IfNotPresent
        command: ["python3", "entrypoint.py", "--init-orderbook"]
        env:
        - name: OB__ORDERBOOK__MID_PRICE
          value: "50.0"
        - name: OB__ORDERBOOK__SPREAD
          value: "1.0"
        - name: OB__ORDERBOOK__QUANTITY
          value: "100"
        - name: OB__KAFKA__BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
        - name: OB__KAFKA__SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: CONFIG_PATH
          value: /app/task.conf
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Never