service:
  type: ClusterIP
  port: 8086

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 250m

config:
  http:
    enabled: true
    bind-address: ":8086"
    auth-enabled: true

setDefaultUser:
  enabled: true
  user: admin
  password: admin