---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: candle-stick-job
spec:
  image: local/flink-jobs:latest
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink-jobs/candle-stick-job-1.0.jar
    parallelism: 2
    upgradeMode: stateless