---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Release.Name }}-kafka-init-orderbook-job
  name: {{ .Release.Name }}-kafka-init-orderbook-job
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-init-orderbook-job
    spec:
      containers:
      - name: kafka-init-orderbook
        image: {{ .Values.kafkaInit.image.repository }}:{{ .Values.orderbook.image.tag }}
        imagePullPolicy: IfNotPresent
        command: ["python3", "entrypoint.py", "--init-orderbook"]
        env:
        - name: OB__ORDERBOOK__MID_PRICE
          value: {{ .Values.kafkaInit.midPrice | quote }}
        - name: OB__ORDERBOOK__SPREAD
          value: {{ .Values.kafkaInit.spread | quote }}
        - name: OB__ORDERBOOK__QUANTITY
          value: {{ .Values.kafkaInit.quantity | quote }}
        - name: OB__KAFKA__BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
        - name: OB__KAFKA__SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: CONFIG_PATH
          value: /app/task.conf
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Never