apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-orderbook
  name: {{ .Release.Name }}-orderbook
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-orderbook
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-orderbook
    spec:
      containers:
        - name: orderbook
          image: {{ .Values.orderbook.image.repository }}:{{ .Values.orderbook.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: OB__KAFKA__BOOTSTRAP_SERVERS
              value: bitnami-kafka:9092
            - name: OB__KAFKA__SECURITY_PROTOCOL
              value: PLAINTEXT
          resources:
            requests:
              cpu: {{ .Values.orderbook.resources.requests.cpu }}
              memory: {{ .Values.orderbook.resources.requests.memory }}
            limits:
              cpu: {{ .Values.orderbook.resources.limits.cpu }}
              memory: {{ .Values.orderbook.resources.limits.memory }}