---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-traderpool
  name: {{ .Release.Name }}-traderpool
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-traderpool
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-traderpool
    spec:
      containers:
      - name: traderpool
        image: {{ .Values.traderpool.image.repository }}:{{ .Values.traderpool.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: OB__KAFKA__TOPICS_CONFIG
            value: /app/topics_config.yaml
          - name: OB__KAFKA__BOOTSTRAP_SERVERS
            value: bitnami-kafka:9092
          - name: OB__KAFKA__SECURITY_PROTOCOL
            value: PLAINTEXT
          - name: OB__CONSUMER__OFFSET_RESET
            value: earliest
          - name: OB__CONSUMER__ENABLE_AUTO_COMMIT
            value: "false"
          - name: OB__CONSUMER__CONSUME_SIZE
            value: "32"
          - name: OB__CONSUMER__CONSUME_TIMEOUT
            value: "0.5"
          - name: CONFIG_PATH
            value: /app/task.conf
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: NUM_TRADERS
            value: {{ .Values.traderpool.numTraders | quote }}
        resources:
          requests:
            cpu: {{ .Values.traderpool.resources.requests.cpu }}
            memory: {{ .Values.traderpool.resources.requests.memory }}
          limits:
            cpu: {{ .Values.traderpool.resources.limits.cpu }}
            memory: {{ .Values.traderpool.resources.limits.memory }}