---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Release.Name }}-kafka-init-topics-job
  name: {{ .Release.Name }}-kafka-init-topics-job
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-init-topics-job
    spec:
      containers:
      - name: kafka-init-topics
        image: {{ .Values.kafkaInit.image.repository }}:{{ .Values.orderbook.image.tag }}
        imagePullPolicy: IfNotPresent
        command: ["python3", "entrypoint.py", "--init-topics"]
        env:
        - name: OB__KAFKA__TOPICS_CONFIG
          value: /app/topics_config.yaml
        - name: OB__KAFKA__BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
        - name: OB__KAFKA__SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: CONFIG_PATH
          value: /app/task.conf
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Never