---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderbook
  name: orderbook-deployment
  namespace: orderbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderbook
  template:
    metadata:
      labels:
        app: orderbook
    spec:
      containers:
      - name: orderbook
        image: local/orderbook
        imagePullPolicy: IfNotPresent