apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderbook
  name: orderbook-pod
  namespace: orderbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderbook
  template:
    metadata:
      labels:
        app: orderbook
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: orderbook
          image: local/orderbook:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OB__KAFKA__BOOTSTRAP_SERVERS
              value: bitnami-kafka:9092
            - name: OB__KAFKA__SECURITY_PROTOCOL
              value: PLAINTEXT
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"