---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: analytics
spec:
  type: NodePort
  selector:
    clickhouse.altinity.com/chi: my-clickhouse
  ports:
    - name: native
      port: 9000
      targetPort: 9000
      nodePort: 30900