{
 "title": "Kafka Metrics",
 "description": "Kafka resource",
 "tags": [ "Kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "description": "Rate of messages produced per second.",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[5m]))",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Kafka Brokers Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Kafka Topics Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_current_offset)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Partitions Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_partitions)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}