---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderbook
  name: orderbook-pod-v2
  namespace: orderbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderbook
  template:
    metadata:
      labels:
        app: orderbook
    spec:
      containers:
      - name: orderbook
        image: local/orderbook_v2:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: OB__KAFKA__BOOTSTRAP_SERVERS
          value: bitnami-kafka:9092
        - name: OB__KAFKA__SECURITY_PROTOCOL
          value: PLAINTEXT