global:
  security:
    allowInsecureImages: true

image:
  repository: local/spark
  tag: 3.5.5
  pullPolicy: IfNotPresent

master:
  replicaCount: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  containerPorts:
    http: 8080
    cluster: 7077
  extraEnvVars:
    - name: SPARK_MASTER_OPTS
      value: "-Dspark.ui.port=8080"

worker:
  replicaCount: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  extraEnvVars:
    - name: SPARK_WORKER_OPTS
      value: ""

service:
  type: ClusterIP
  ports:
    http: 8080
    cluster: 7077